name: pr-actions
on: 
  push:
    branches: [main]
jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with: 
          node-version: '14'
      - run: npm install
      - run: npm run cypress:run
