name: pr-actions
on: 
  pull_request:
    branches:
      - 'main'
jobs:
  Run-Cypress-PR:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run cypress:run
